name: Update VPN Configs

on:
  schedule:
    - cron: '0 * * * *' # اجرا هر ساعت
  workflow_dispatch: # امکان اجرای دستی

jobs:
  update-configs:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run fetch_configs script
      run: python fetch_configs.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add merged_configs.txt
        git diff-index --quiet HEAD || git commit -m "Update VPN configs"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

